apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: 'true'
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    name: backend-svc
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: server
  selector:
    name: backend-pod
    app: {{ .Values.appName }}
