apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-set
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: cache-set
    app: {{ .Values.appName }}
spec:
  replicas: 1  
  selector:
    matchLabels:
      name: cache-pod
      app: {{ .Values.appName }}
  template:
    metadata:
      name: cache-pod
      labels:
        name: cache-pod
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: cache
        image: redis:alpine
        ports:
        - containerPort: 6379