apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-set
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: zookeeper-set
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-pod
      app: {{ .Values.appName }}
  template:
    metadata:
      name: zookeeper-pod
      labels:
        name: zookeeper-pod
        app: {{ .Values.appName }}
    spec:
      volumes:
      - name: zookeeper-storage
        persistentVolumeClaim:
          claimName: zookeeper-claim
      containers:
      - name: zookeeper
        image: zookeeper
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: zookeeper-storage
          mountPath: "/data"
