appName: quectolink
namespace: default
ingressClass: nginx
replicas:
  backend: 3
  frontend: 3
images:
  backend_image: 
    name: programmingninjas/quectolink-backend
    tag: 0.0.2
  frontend_image: 
    name: programmingninjas/quectolink
    tag: 0.0.2
configmap:
  backend_data:
    PORT: "5000"
    MONGO_URI: mongodb://mongo:27017/quectolink
  frontend_data:
    IP: https://quecto.fr.to
