appName: quectolink
namespace: default
ingressClass: nginx
replicas:
  backend: 1
  frontend: 1
images:
  backend_image: 
    name: programmingninjas/argolink-backend
    tag: 0.0.2
  frontend_image: 
    name: programmingninjas/argolink-frontend
    tag: 0.0.1
configmap:
  backend_data:
    PORT: "5000"
    MONGO_URI: mongodb://mongo:27017/quectolink
  frontend_data:
    IP: https://quecto.fr.to
